### ISSUE TITLE
Prefix hardcoded in help messages

### ISSUE THREAD

**Issue by JUtupe** [DankMemer/Octave#42]
**Describe the bug**
Prefix is hardcoded in help messages

**To Reproduce**
1. change prefix to something different than "_"
2. type any help command
3. help message contains default "prefix"

**Expected behavior**
Prefix in help message should be equal to server's prefix

**Screenshots**
![image](https://user-images.githubusercontent.com/33636616/76988314-cd395280-6944-11ea-9a29-82e09c8f5e37.png)

**Comment by Devoxin** [comment]
Should be fixed in the rewrite.
