### ISSUE TITLE
How to reset prefix for Octave?

### ISSUE THREAD

**Issue by rivalDevYP** [DankMemer/Octave#47]
**Describe the bug**
Set prefix to "<at_sign>Octave", got a message saying prefix set to "\<at_sign>201503408652419073". 

Tried to play some music using <at_sign>Octave youtube music_title, but no response

_help, <at_sign>Octave help, <at_sign>Octave _help doesn't work

**To Reproduce**
N/A

**Expected behavior**
A help menu when running <at_sign>Octave help or _help

**Screenshots**
N/A

**Additional context**
N/A

**Comment by octave** [comment]
Not sure you wanted to tag me?

**Comment by rivalDevYP** [comment]
> Not sure you wanted to tag me?

nope. sorry about that.

**Comment by Bendall6456** [comment]
To reset prefix, you can ping pass `octave settings prefix reset` to place it back to the default prefix of `_`.

**Comment by rivalDevYP** [comment]
Ping as in "<at_sign>Octave octave settings prefix reset" ?

**Comment by rivalDevYP** [comment]
Ping as in "<at_sign>Octave octave settings prefix reset" ?

![image](https://user-images.githubusercontent.com/43413546/78198098-86278300-7455-11ea-9dfa-d535f49e1282.png)

**Comment by Bendall6456** [comment]
no without the @ symbol for example `octave settings prefix reset` do NOT add the @ symbol because it will not work.

**Comment by rivalDevYP** [comment]
it worked!

thank you!

**Comment by Bendall6456** [comment]
np!
