### ISSUE TITLE
Youtube lyrics

### ISSUE THREAD

**Issue by SLDDL** [DankMemer/Octave#57]
Have a command to give the YouTube lyrics of a video should be nice.

**Comment by Devoxin** [comment]
![](https://serux.pro/76e9a5edfb.png)

already exists?

**Comment by SLDDL** [comment]
> ![](https://serux.pro/76e9a5edfb.png)
> 
> already exists?

When i try to enable the lyrics of a video is say that it doesn't find any ( the video has lyrics )
![IMG_20200716_143808.jpg](https://user-images.githubusercontent.com/29633620/87671761-2d64c780-c772-11ea-955a-ae7b2883136f.jpg)

**Comment by Devoxin** [comment]
We rely on a third party service for lyrics (which itself uses Genius). You need the *actual* title of the song (with as few garbage characters/symbols in the title as possible) to get the best results. I believe this is what you're looking for?
![Screenshot_20200716-135343_Chrome](https://user-images.githubusercontent.com/15076404/87673119-ea075a80-c76b-11ea-91fe-8d6939f79eeb.jpg)
