### ISSUE TITLE
Playlist names can contain pings

### ISSUE THREAD

**Issue by pixelomer** [DankMemer/Octave#59]
**Describe the bug**
One can name a playlist

    a`@here @everyone`a

to ping everyone.

**Expected behavior**
It shouldn't ping everyone.

**Screenshots**
<img width="774" alt="Screen Shot 2020-08-04 at 22 10 58" src="https://user-images.githubusercontent.com/37103802/89335158-522cca80-d6a0-11ea-99c4-addcf9c6f86f.png">

**Comment by Devoxin** [comment]
Fixed in 8cdf37e
